name: Publish to Blockless
on:
  workflow_dispatch:
  repository_dispatch:

jobs:
  publish-on-blockless:
    runs-on: ubuntu-latest

    permissions:
      id-token: write # This is required for requesting the JWT
      contents: write  # This is required for actions/checkout

    steps:
      - uses: actions/checkout@v2
      - name: Blockless Action Setup
        uses: txlabs/github-action-blockless-setup@v0.0.5
        with:
          BLOCKLESS_ENDPOINT_URL: https://cold-heron-20.deno.dev
      - name: Blockless Function Publish
        uses: txlabs/github-action-blockless-deploy@v0.0.3
